/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: skFilter2.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 29-Aug-2024 20:20:07
 */

/* Include Files */
#include "skFilter2.h"
#include "skFilter2_data.h"
#include "skFilter2_initialize.h"
#include "skFilter2_types.h"

/* Function Definitions */
/*
 * DOFILTER Filters input x and returns output y.
 *
 * Arguments    : const short x_data[]
 *                const int x_size[1]
 *                float y_data[]
 *                int y_size[2]
 * Return Type  : void
 */
void skFilter2(const short x_data[], const int x_size[1], float y_data[],
               int y_size[2])
{
  dsp_BiquadFilter_0 *obj;
  int i;
  int ioIdx;
  if (!isInitialized_skFilter2) {
    skFilter2_initialize();
  }
  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15. */
  /*  Generated on: 29-Aug-2024 19:36:29 */
  /*  To generate C/C++ code from this function use the codegen command. */
  /*  Type 'help codegen' for more information. */
  obj = &Hd.cSFunObject;
  /* System object Outputs function: dsp.BiquadFilter */
  y_size[0] = x_size[0];
  y_size[1] = 1;
  ioIdx = 0;
  if (Hd.cSFunObject.W1_PreviousNumChannels == -1) {
    Hd.cSFunObject.W1_PreviousNumChannels = 1;
  }
  for (i = 0; i < x_size[0]; i++) {
    float denAccum;
    float tmpState;
    denAccum = obj->P3_RTP3COEFF[0] * (float)x_data[ioIdx];
    denAccum -= obj->P2_RTP2COEFF[0] * obj->W0_FILT_STATES[0];
    tmpState = denAccum - obj->P2_RTP2COEFF[1] * obj->W0_FILT_STATES[1];
    denAccum = obj->P1_RTP1COEFF[0] * tmpState;
    denAccum += obj->W0_FILT_STATES[0] * obj->P1_RTP1COEFF[1];
    denAccum += obj->W0_FILT_STATES[1] * obj->P1_RTP1COEFF[2];
    obj->W0_FILT_STATES[1] = obj->W0_FILT_STATES[0];
    obj->W0_FILT_STATES[0] = tmpState;
    denAccum *= obj->P3_RTP3COEFF[1];
    denAccum -= obj->P2_RTP2COEFF[2] * obj->W0_FILT_STATES[2];
    tmpState = denAccum - obj->P2_RTP2COEFF[3] * obj->W0_FILT_STATES[3];
    denAccum = obj->P1_RTP1COEFF[3] * tmpState;
    denAccum += obj->W0_FILT_STATES[2] * obj->P1_RTP1COEFF[4];
    y_data[ioIdx] = denAccum + obj->W0_FILT_STATES[3] * obj->P1_RTP1COEFF[5];
    obj->W0_FILT_STATES[3] = obj->W0_FILT_STATES[2];
    obj->W0_FILT_STATES[2] = tmpState;
    ioIdx++;
  }
}

/*
 * DOFILTER Filters input x and returns output y.
 *
 * Arguments    : void
 * Return Type  : void
 */
void skFilter2_free(void)
{
  if (!Hd.matlabCodegenIsDeleted) {
    Hd.matlabCodegenIsDeleted = true;
  }
}

/*
 * DOFILTER Filters input x and returns output y.
 *
 * Arguments    : void
 * Return Type  : void
 */
void skFilter2_init(void)
{
  Hd.matlabCodegenIsDeleted = true;
}

/*
 * File trailer for skFilter2.c
 *
 * [EOF]
 */
