# Constants for Sensory Substitution Devce 
# Written by: Sreela Kodali (kodali@stanford.edu) 

BAUD_RATE = 4608000
DATASRC_SD = False
TRANSFER_RAW = False

# Calibration
ACTUATOR_FEEDBACK_MAX = 985
ACTUATOR_FEEDBACK_MIN = 139
ANGLE_DATA_MIN = 5000
ANGLE_DATA_MAX = 10100
ZERO_FORCE = 0.18

# PILOT STUDY
N_TOTAL_TRIALS = 60
ANGLE_TOLERANCE = 12
ANGLE_CONSECUTIVE = 15

# DATA Collection
PATH =  '/Volumes/PIEZO2/'
PATH_LAPTOP = '/Users/Sreela/Documents/School/Stanford/Year3_2/PIEZO2/Data/Pilot/'
PORT_NAME = "/dev/cu.usbmodem71181201"
RUNTIME_LENGTH = 30 # seconds

## DATA PROCESSING CONSTANTS ##
ANGLE_MIN = 180
ANGLE_MAX = 40
ACTUATOR_POSITION_MIN = 0.0
ACTUATOR_POSITION_MAX = 20.0
ACTUATOR_COMMAND_MIN = 46
ACTUATOR_COMMAND_MAX = 130
N_CORR = 20000 # computing the delay
