# Constants for Sensory Substitution Devce 
# Written by: Sreela Kodali (kodali@stanford.edu) 

BAUD_RATE = 4608000
DATASRC_SD = False
TRANSFER_RAW = False


PATH =  '/Volumes/PIEZO2/'
PATH_LAPTOP = '/Users/Sreela/Documents/School/Stanford/Year3_2/PIEZO2/Data/'
PORT_NAME = "/dev/cu.usbmodem71181201"
RUNTIME_LENGTH = 30 # seconds

N_TOTAL_TRIALS = 10
ANGLE_TOLERANCE = 5

# Calibration
ACTUATOR_FEEDBACK_MIN = 142
ACTUATOR_FEEDBACK_MAX = 988
ANGLE_DATA_MIN = 3400
ANGLE_DATA_MAX = 12100
ZERO_FORCE = 0

## DATA PROCESSING CONSTANTS ##
ANGLE_MIN = 180
ANGLE_MAX = 30
ACTUATOR_POSITION_MIN = 0.0
ACTUATOR_POSITION_MAX = 20.0
ACTUATOR_COMMAND_MIN = 46
ACTUATOR_COMMAND_MAX = 130
N_CORR = 20000 # computing the delay
