function y = skFilter_fs32_fpass04(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Dec-2024 04:10:08

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.4;      % Passband Frequency
    % Fstop = 6;        % Stopband Frequency
    % Apass = 1;        % Passband Ripple (dB)
    % Astop = 80;       % Stopband Attenuation (dB)
    % Fs    = 32.1761;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.92349208786039 0.931743950700518; 1 2 1 1 ...
        -1.83493042714072 0.842802356690892], ...
        'ScaleValues', [0.00206296571003269; 0.00196798238754268; 1]);
end

s = single(x);
y = step(Hd,s);

