function y = skFilterBands(x)
%SKFILTERBANDS Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Dec-2024 05:33:51

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % IIR Least P-th norm Arbitrary magnitude filter designed using the
    % % IIRLPNORM function.
    %
    % % All frequency values are in Hz.
    % Fs = 32;  % Sampling Frequency
    %
    % Nb   = 12;                      % Numerator Order
    % Na   = 12;                      % Denominator Order
    % F    = [0 0.5 1 4 5 10 11 14];  % Frequency Vector
    % E    = [0 0.5 1 4 5 10 11 14];  % Frequency Edges
    % A    = [1 1 0 0 1 1 0 0];       % Amplitude Vector
    % W    = [1 1 1 1 1 1 1 1];       % Weight Vector
    % P    = [2 128];                 % P'th norm
    % dens = 20;                      % Density Factor
    %
    % [b,a,err,sos_var,g] = iirlpnorm(Nb, Na, F/(Fs/2), E/(Fs/2), A, W, P, ...
    %                                 {dens});
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.95391174101848 0.999939606301167 1 ...
        -1.93521547262609 0.946667617735655; 1 -1.4568855359119 ...
        0.999826220473585 1 -1.07367995435919 0.882150244400606; 1 ...
        -1.79496208308054 0.997511233524447 1 -1.09849857768065 ...
        0.160811731147756; 1 -0.225296426529222 0.00191381080116428 1 ...
        -0.536858193329761 0.578600520937723; 1 1.6799273544819 ...
        0.879791972742773 1 0.312114442797324 0.62012504848393; 1 ...
        1.16883444514166 0.992339481626392 1 0.752315885430409 0.89199952979044], ...
        'ScaleValues', [0.0708581425499695; 1; 1; 1; 1; 1; 1]);
end

y = step(Hd,double(x));


% [EOF]
