function y = skFilter_fs32_fpass65(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Dec-2024 18:43:47

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 6.5;      % Passband Frequency
    % Fstop = 16;       % Stopband Frequency
    % Apass = 1;        % Passband Ripple (dB)
    % Astop = 80;       % Stopband Attenuation (dB)
    % Fs    = 32.1761;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 0.0370399282879489 0.171815415551449], ...
        'ScaleValues', [0.302213835959849; 1]);
end

s = single(x);
y = step(Hd,s);

