function y = skFilter2(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 29-Aug-2024 19:36:29

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.08;    % Passband Frequency
    % Fstop = 1.5;     % Stopband Frequency
    % Apass = 1;       % Passband Ripple (dB)
    % Astop = 80;      % Stopband Attenuation (dB)
    % Fs    = 4.9261;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.86490642592356 0.880227994363408; 1 1 0 1 ...
        -0.879767456577723 0], ...
        'ScaleValues', [0.00383039210996134; 0.0601162717111387; 1]);
end

s = single(x);
y = step(Hd,s);

