function y = skFilter_fs50_fpass08(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Dec-2024 03:14:49

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.08;  % Passband Frequency
    % Fstop = 1.5;   % Stopband Frequency
    % Apass = 1;     % Passband Ripple (dB)
    % Astop = 80;    % Stopband Attenuation (dB)
    % Fs    = 50;    % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.99079042816979 0.990931462318008; 1 2 1 1 ...
        -1.97810597298406 0.978246108523708], ...
        'ScaleValues', [3.52585370537931e-05; 3.50338849121889e-05; 1]);
end

s = single(x);
y = step(Hd,s);

