function y = skFilter5(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 28-Dec-2024 03:08:11

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.05;    % Passband Frequency
    % Fstop = 1;       % Stopband Frequency
    % Apass = 1;       % Passband Ripple (dB)
    % Astop = 80;      % Stopband Attenuation (dB)
    % Fs    = 4.9261;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.93835257461046 0.943890113386536; 1 2 1 1 ...
        -1.86438195049148 0.869708167960628], ...
        'ScaleValues', [0.0013843846940184; 0.00133155436728701; 1]);
end

s = single(x);
y = step(Hd,s);

