function y = skFilterBS2(x)
%SKFILTERBS2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 29-Dec-2024 01:45:05

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % IIR Least P-th norm Arbitrary magnitude filter designed using the
    % % IIRLPNORM function.
    %
    % % All frequency values are in Hz.
    % Fs = 32;  % Sampling Frequency
    %
    % Nb   = 12;                    % Numerator Order
    % Na   = 12;                    % Denominator Order
    % F    = [0 0.5 1 4 5 8 9 16];  % Frequency Vector
    % E    = [0 0.5 1 4 5 8 9 16];  % Frequency Edges
    % A    = [1 1 0 0 1 1 0 0];     % Amplitude Vector
    % W    = [1 1 1 1 1 1 1 1];     % Weight Vector
    % P    = [2 128];               % P'th norm
    % dens = 20;                    % Density Factor
    %
    % [b,a,err,sos_var,g] = iirlpnorm(Nb, Na, F/(Fs/2), E/(Fs/2), A, W, P, ...
    %                                 {dens});
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.95437619257733 0.999814342219644 1 ...
        -1.94786237776804 0.959206851874166; 1 -1.45210487090457 ...
        0.999831244516523 1 -0.730355280527923 0.703616844034347; 1 ...
        -1.07566929652837 0.174013109334646 1 -1.08951560270548 ...
        0.904962007801766; 1 -1.79016086313796 0.9996469072265 1 ...
        -1.89225427624002 0.896835631904158; 1 0.447585693057881 ...
        0.999580315772861 1 -0.220569802790316 0.713197577532055; 1 ...
        1.17401918969258 0.867514292877254 1 0.0377081448830765 ...
        0.90806734721756], ...
        'ScaleValues', [0.0310442719038114; 1; 1; 1; 1; 1; 1]);
end

y = step(Hd,double(x));


% [EOF]
