# Constants for Sensory Substitution Devce 
# Written by: Sreela Kodali (kodali@stanford.edu) 

BAUD_RATE = 4608000
DATASRC_SD = False # Where to save data, on SD card if true. Else on laptop
TRANSFER_RAW = False # save raw values if true. else process values with processing constants and calibration

## SYSTEM DIRECTORY PATHS ##
PATH_SD =  '/Volumes/PIEZO2/'
PATH_HOME = '/Users/Sreela/Documents/School/Stanford/Year3_2/PIEZO2/JND_Study/'
PATH_LAPTOP = PATH_HOME + 'JND_Data/'
#PATH_LAPTOP = '/Users/Sreela/Documents/School/Stanford/Year3_2/PIEZO2/Data/systemEvaluation/'
#PATH_LAPTOP = '/Users/Sreela/Documents/School/Stanford/Year3_2/PIEZO2/Data/timing/'
PORT_NAME = "/dev/cu.usbmodem131754901" #"/dev/cu.usbmodem131755101"#"/dev/cu.usbmodem43098001"#"/dev/cu.usbmodem71181201"

## DATA PROCESSING CONSTANTS ##
ANGLE_MIN = 180
ANGLE_MAX = 40 # 0 for FLEX_SENSOR
ACTUATOR_POSITION_MIN = 0.0 # I should measure this
ACTUATOR_POSITION_MAX = 20.0
ACTUATOR_COMMAND_MIN = 47  
ACTUATOR_COMMAND_MAX = 139#130

# RUNTIME_LENGTH_ARM = 1000 # seconds #only for serialAngleArm.py
# RUNTIME_LENGTH = 10 # seconds #for readProcessSerial.py
# N_CORR = 20000 # computing the delay in processPlotData.py


# ## DEFAULT CALIBRATION VALUES ##
ANGLE_DATA_MIN = 40	# when using keyboard
ANGLE_DATA_MAX = 180
# ANGLE_DATA_MIN = 0   # when reading raw flex values
# ANGLE_DATA_MAX = 11600
# ANGLE_DATA_MIN = -25.48 # when calibrating flex sensor
# ANGLE_DATA_MAX = 95.24

# ACTUATOR_FEEDBACK_MAX = 988
# ACTUATOR_FEEDBACK_MIN = 145
# ZERO_FORCE = 0.00#2023-02-15_11-44_subjects
ACTUATOR_FEEDBACK_MAX = 973
ACTUATOR_FEEDBACK_MIN = 49

ZERO_FORCE = 255
USER_MIN_FORCE_DATA = 255
USER_MAX_FORCE_DATA = 255
USER_MIN_ACTUATOR_COMMAND = 71
USER_MAX_ACTUATOR_COMMAND = 120
USER_MIN_ACTUATOR_AVG = 71
USER_MAX_ACTUATOR_AVG = 120

#2024-04-03_16-57_subjectsreela
ACTUATOR_FEEDBACK_MAX = 961
ACTUATOR_FEEDBACK_MIN = 28
ZERO_FORCE = 257
USER_MIN_FORCE_DATA = 275
USER_MAX_FORCE_DATA = 397
USER_MIN_ACTUATOR_COMMAND = 61
USER_MAX_ACTUATOR_COMMAND = 132
USER_MIN_ACTUATOR_AVG = 61
USER_MAX_ACTUATOR_AVG = 132
ZERO_FORCE = 261
USER_MIN_FORCE_DATA = 269
USER_MAX_FORCE_DATA = 368
USER_MIN_ACTUATOR_COMMAND = 63
USER_MAX_ACTUATOR_COMMAND = 136
USER_MIN_ACTUATOR_AVG = 62
USER_MAX_ACTUATOR_AVG = 134
ZERO_FORCE = 264
USER_MIN_FORCE_DATA = 274
USER_MAX_FORCE_DATA = 368
USER_MIN_ACTUATOR_COMMAND = 71
USER_MAX_ACTUATOR_COMMAND = 135
USER_MIN_ACTUATOR_AVG = 65
USER_MAX_ACTUATOR_AVG = 134
